### ISSUE TITLE
Failed to install in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by byteshiva** [constcharptr/lyrebird#39]
Failed to install in Ubuntu 20.04 LTS
log details
```
$ sudo dpkg -i lyrebird_1.1.0-1.deb
(Reading database ... 439479 files and directories currently installed.)
Preparing to unpack lyrebird_1.1.0-1.deb ...
Unpacking lyrebird (1.1.0-1) over (1.1.0-1) ...
dpkg: dependency problems prevent configuration of lyrebird:
 lyrebird depends on python3-toml; however:
  Package python3-toml is not installed.
 lyrebird depends on python-gobject; however:
  Package python-gobject is not installed.
 lyrebird depends on libsox-fmt-pulse; however:
  Package libsox-fmt-pulse is not installed.

dpkg: error processing package lyrebird (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 lyrebird
$ 
```

**Comment by harrego** [comment]
After installing a package through `dpkg` you should always run `apt install --fix-missing` to grab all the needed dependencies. Let me know if you get it working.

**Comment by byteshiva** [comment]
> After installing a package through `dpkg` you should always run `apt install --fix-missing` to grab all the needed dependencies. Let me know if you get it working.

The installation went thru fine but unable to open GUI on Ubuntu 20.04 LTS

Details available at
https://gist.github.com/byteshiva/5a24ffab7195eda3721ff41a79761846

**Comment by harrego** [comment]
@byteshiva This is an odd distro specific bug that we've seen, #13 has a fix that worked for some.

**Comment by acoolstraw** [comment]
pls fix, `--fix-missing` doesn't work.
