### ISSUE TITLE
discord link broken

### ISSUE THREAD

**Issue by kfatehi** [constcharptr/lyrebird#42]
this is a nice project. thank you for creating it. the discord invite link needs to be replaced.

**Comment by MegaShinySnivy** [comment]
This project appears to be abandoned by the maintainer--the discord invite seems to direct to a server that doesn't exist, at least not anymore. If they're still around then please, speak up!

**Comment by harrego** [comment]
Not sure why the link broke, but here is a new one I'll also add to the README: https://discord.gg/mvCSwYVe5t
