### ISSUE TITLE
No Input Detected via Lyrebird Virtual Input

### ISSUE THREAD

**Issue by Hielyr** [constcharptr/lyrebird#43]
OS: Pop!_OS 20.04 LTS (Ubuntu derivative)

Issue: When switching from my default audio input device to the Lyrebird Virtual Input, no applications can detect any audio. I have tried this with multiple programs, including Audacity, Discord, and OBS Studio.

```
us3r@workstation:~/Desktop/lyrebird-1.1.0$ ./install.sh 
[lyrebird] Installing Lyrebird to prefix: /home/us3r/.local
[lyrebird] Installing Python modules: toml
Requirement already satisfied: toml in /usr/lib/python3/dist-packages (0.10.0)

[lyrebird] Copying app/ to: /home/us3r/.local/share/lyrebird
[lyrebird] Copying icon.png to: /home/us3r/.local/share/lyrebird
[lyrebird] Copying app.py to: /home/us3r/.local/share/lyrebird
[lyrebird] Copying lyrebird to: /home/us3r/.local/bin
[lyrebird] Setting permissions 755 recursively for: /home/us3r/.local/share/lyrebird

[lyrebird] Copying lyrebird.desktop to: /home/us3r/.local/share/applications
[lyrebird] Setting permission 644 for: /home/us3r/.local/share/applications/lyrebird.desktop

[lyrebird] Installed Lyrebird v1.1
us3r@workstation:~/Desktop/lyrebird-1.1.0$ lyrebird 
Module module-null-sink not loaded.
Module module-remap-source not loaded.
Loaded null output sink (0), and remap sink (0)
```

I have verified that I have the correct prerequisites installed as listed in the ReadMe, and I have tried both the .deb package and the .sh script installations with both having the same result.

**Comment by MegaShinySnivy** [comment]
I am having this issue with the AUR package as well. SoX is picking up my input, but it doesn't appear to be making it to the virtual input device. Are you having the same issue, or should I open a new one?

**Comment by Hielyr** [comment]
I'm not too sure. I kinda gave up about a week after I opened this issue and uninstalled everything, so I can't say that I remember if SoX was registering anything or not.

Hopefully a new release comes out soon and I can try again, but until that point I'm done fiddling with it.

**Comment by MegaShinySnivy** [comment]
It seems to have broken really bad with the most recent discord update--it was working somewhat for a while, but now it is just dead silent on LBVI. Back to quiet for me.

**Comment by harrego** [comment]
Hey everyone, I just did a clean install on my Arch box from the AUR and didn't have any issues. The issue you're both having sounds like SoX is selecting the wrong recording device. To fix this try going to `pavucontrol`, find SoX under the "Recording" tab and change the audio device listed alongside it to your microphone.

Let me know how it goes.

**Comment by MegaShinySnivy** [comment]
> Hey everyone, I just did a clean install on my Arch box from the AUR and didn't have any issues. The issue you're both having sounds like SoX is selecting the wrong recording device. To fix this try running Lyrebird and toggle it on, open `pavucontrol`, find SoX under the "Recording" tab and change the audio device listed alongside it to your microphone.
> 
> Let me know how it goes.

SoX has the right device, but it doesn't appear to be making it to the virtual output. If I swap the SoX _output_ to something that isn't null, I can hear it come through just fine.

**Comment by MegaShinySnivy** [comment]
I also tried a fresh installation. Nothing there, I'm afraid, even with a clean build.

**Comment by lecblue** [comment]
@harrego
" . . . To fix this try running Lyrebird and toggle it on, open pavucontrol, find SoX under the "Recording" tab and change the audio device listed alongside it to your microphone. "
Perfect! Works like a charm.
Older Dell laptop. Internal microphone. Plugged in headphones.
Lubuntu fresh install.
Installed Audacity.
Made sure Audacity could record and play back from my mic.
Installed lyrebird from command line. Used sudo. Install complained about a few dependencies. Installed each dependency. No issues.
Lyrebird then installed from the command line with sudo. No issues.
Tried lyrebird. No errors, but no sound. Tried several things with pavucontrol and Audacity settings. No sound. But Audacity still worked straight from mic.
Looked up this thread. Applied suggested changes. Lyrebird was working in less than 2 minutes.
SoX (under Recording) does not list my microphone. It did list Built-in Audio. Built-in Audio (under Input Devices) lists my microphone.
Tried several settings. Got a good laugh. Thanks! Just what I wanted.

**Comment by MegaShinySnivy** [comment]
https://user-images.githubusercontent.com/53403722/104106226-def43980-5279-11eb-876d-821e16e2d446.mp4

Attached is a video containing my current settings within pavucontrol and the results. Mic input is me saying the same phrase over and over.

**Comment by lecblue** [comment]
I looked at your video a couple of times. I can't say I can see the issue. I am attaching images of my pavucontrol settings. 
In my case, Audacity is set to use the "default" recording device. I have Lyrebird Virtual Input set as a fallback device and the internal mic not set as a fallback device. When you turn on Lyrebird it creates the SoX application. That application is set to built-in audio. The built-in audio is set to use the internal mic. 
In your case I can see where you have SoX recording from Corsair HS45. But, I don't see Corsair HS45 pointing to a microphone. I don't have that set up so I can't tell what it should be. 
I'm big on testing "normal" before making a change. So in my images, the lyrebird01, 01a, 01b, 01c are without lyrebird turned on. Images lyrebird02, 02a, 02b and 02c are with lyrebird turned on. For me, it was really making sure the SoX app created by lyrebird was listening to my mic. In the first images on both sets you can see an audio track was created in both cases 

![lyrebird01](https://user-images.githubusercontent.com/77198023/104113376-d5d98b80-52be-11eb-8d4e-5426a3bc31b9.jpg)
![lyrebird01a](https://user-images.githubusercontent.com/77198023/104113377-d8d47c00-52be-11eb-897a-2e620bc4f76e.jpg)
![lyrebird01b](https://user-images.githubusercontent.com/77198023/104113379-dc680300-52be-11eb-9054-e379f05f78d1.jpg)
![lyrebird01c](https://user-images.githubusercontent.com/77198023/104113380-e0942080-52be-11eb-997d-a3e1c738a11d.jpg)
![lyrebird02](https://user-images.githubusercontent.com/77198023/104113382-e427a780-52be-11eb-9d9f-12e27df7658f.jpg)
![lyrebird02a](https://user-images.githubusercontent.com/77198023/104113385-e7bb2e80-52be-11eb-8105-4848ec12fd07.jpg)
![lyrebird02b](https://user-images.githubusercontent.com/77198023/104113388-eab61f00-52be-11eb-9791-e327111ed432.jpg)
![lyrebird02c](https://user-images.githubusercontent.com/77198023/104113390-eee23c80-52be-11eb-8285-9ac08c8d1e14.jpg)

HTH

**Comment by MegaShinySnivy** [comment]
> I looked at your video a couple of times. I can't say I can see the issue. I am attaching images of my pavucontrol settings.
> In my case, Audacity is set to use the "default" recording device. I have Lyrebird Virtual Input set as a fallback device and the internal mic not set as a fallback device. When you turn on Lyrebird it creates the SoX application. That application is set to built-in audio. The built-in audio is set to use the internal mic.
> In your case I can see where you have SoX recording from Corsair HS45. But, I don't see Corsair HS45 pointing to a microphone. I don't have that set up so I can't tell what it should be.
> I'm big on testing "normal" before making a change. So in my images, the lyrebird01, 01a, 01b, 01c are without lyrebird turned on. Images lyrebird02, 02a, 02b and 02c are with lyrebird turned on. For me, it was really making sure the SoX app created by lyrebird was listening to my mic. In the first images on both sets you can see an audio track was created in both cases

HS45 is a USB DAC that my headset is connected to, as my motherboard's internal audio in/out is non-functional on Linux due to a driver missing (thank you broadcom). It handles both audio in and audio out. If I make SoX audio out and point it at something else (like my actual audio out) I can hear my altered voice just fine. But once I point it to LBVI it fails to make it through. Is there some sort of verbose mode I could run it in to generate logs?

**Comment by lecblue** [comment]
As a user, the best I can do is show you my settings and see what is different.
"I can hear my altered voice. . ." This is good. So there are settings that allow lyrebird itself to work.
I can make a few guesses and suggest a place to look. Beyond that, there is not much I can do.

My guess is this is still a pulse audio setting issue. In my settings, I specify exactly which device should go to lyrebird input and exactly which device goes to output. From the video, I did not see that option for you. Not knowing the internals of any of this software, my guess is lyrebird has no control over which device it uses for input or where its output goes.

I found an article on troubleshooting a current pulse audio issue.
**This article and issue has nothing to do with lyrebird.** 
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1087
But, it does give directions on how to use verbose mode for pulse audio.
pulseaudio -vvvvv > /tmp/pulse-verbose.log 2>&1

I am guessing the logged output would show you what all of your devices are and who routed to what. I have not used this mode. I don't know what the output provides. A guess is to that the driverless broadcom interface may still be causing you issues. The truth is, I don't have a clue.

**Comment by MegaShinySnivy** [comment]
> As a user, the best I can do is show you my settings and see what is different.
> "I can hear my altered voice. . ." This is good. So there are settings that allow lyrebird itself to work.
> I can make a few guesses and suggest a place to look. Beyond that, there is not much I can do.
>
> My guess is this is still a pulse audio setting issue. In my settings, I specify exactly which device should go to lyrebird input and exactly which device goes to output. From the video, I did not see that option for you. Not knowing the internals of any of this software, my guess is lyrebird has no control over which device it uses for input or where its output goes.

It could be I have a more recent version of PA (or pavucontrol) that removed this functionality.
 
> I found an article on troubleshooting a current pulse audio issue.
> **This article and issue has nothing to do with lyrebird.**
> https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1087
> But, it does give directions on how to use verbose mode for pulse audio.
> pulseaudio -vvvvv > /tmp/pulse-verbose.log 2>&1

Ran it, PA became very laggy after I did--understandable, of course. I ran the same sentence test to generate activity... For naught, as you will see below.

> I am guessing the logged output would show you what all of your devices are and who routed to what. I have not used this mode. I don't know what the output provides. A guess is that the driverless broadcom interface may still be causing you issues. The truth is, I don't have a clue.

A logged output only showed PulseAudio startup, and nothing about routing information. Here is a cat of the log if you think it will be useful. Seriously considering clearing my PA configs and seeing what that does.
`I: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation not permitted`
`I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation not permitted`
`D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.`
`D: [pulseaudio] core-util.c: RealtimeKit worked.`
`I: [pulseaudio] core-util.c: Successfully gained nice level -11.`
`I: [pulseaudio] main.c: This is PulseAudio 14.0`
`D: [pulseaudio] main.c: Compilation host: x86_64`
`D: [pulseaudio] main.c: Compilation CFLAGS: Not yet supported on meson`
`D: [pulseaudio] main.c: Running on host: Linux x86_64 5.10.5-arch1-1 #1 SMP PREEMPT Thu, 07 Jan 2021 09:50:43 +0000`
`D: [pulseaudio] main.c: Found 16 CPUs.`
`I: [pulseaudio] main.c: Page size is 4096 bytes`
`D: [pulseaudio] main.c: Compiled with Valgrind support: no`
`D: [pulseaudio] main.c: Running in valgrind mode: no`
`D: [pulseaudio] main.c: Running in VM: no`
`D: [pulseaudio] main.c: Running from build tree: no`
`D: [pulseaudio] main.c: Optimized build: yes`
`D: [pulseaudio] main.c: All asserts enabled.`
`I: [pulseaudio] main.c: Machine ID is (redacted as it doesn't appear to matter and was really long)` 
`I: [pulseaudio] main.c: Session ID is 5.`
`I: [pulseaudio] main.c: Using runtime directory /run/user/1000/pulse.`
`I: [pulseaudio] main.c: Using state directory /home/rex/.config/pulse.`
`I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-14.0/modules.`
`I: [pulseaudio] main.c: Running in system mode: no`
`E: [pulseaudio] pid.c: Daemon already running.`
`E: [pulseaudio] main.c: pa_pid_file_create() failed.`

**Comment by harrego** [comment]
@MegaShinySnivy I've screwed around with both Pulse and SoX trying to understand what is happening. Your pavu settings look normal which makes this issue even more confusing. But I think I have a start.

For more background Lyrebird works like this: a sink (Pulse's name for an audio stream) is created named "Lyrebird Output" where SoX takes data from your microphone, processes it and dumps it into this stream. Then, because apps can only use input streams as a mic, a second sink is created named "Lyrebird Input" which is a direct copy of whatever is dumped into "Lyrebird Output" but is masked as an input. Lyrebird Input is just a mask on top of "Monitor of Null Output" (Null Output in this case actually refers to Lyrebird Output).

Because in your case both sinks are empty, it looks as if Pulse is working fine and SoX is not. It seems to capture your mic data as evident by pavu displaying levels under it, but it's failing to dump its stream into Lyrebird Output. This is only my working theory right now.

Could you do two things to help debug this:
1) Run `sox --version`
2) While Lyrebird is open and on, run `sox --buffer 1024 -v 20 -q -t pulseaudio default -t pulseaudio Lyrebird-Output` in your terminal (it will be pre-processed sound). Check if you see any levels by "Monitor of Null Output" or "Lyrebird Input".

Thanks for staying with me on this one!

**Comment by MegaShinySnivy** [comment]
This was solved in the discord server by an eventual reset of the PA config files manually. Since then, it has worked.

**Comment by harrego** [comment]
Thanks everyone for all the help. If anyone has a similar problem please open a new issue.
