### ISSUE TITLE
Using external mic as input device for lyrebird virtual input

### ISSUE THREAD

**Issue by DarkStar1997** [constcharptr/lyrebird#49]
How to use an external mic for voice input to lyrebird instead of default laptop mic?

**Comment by harrego** [comment]
1. Install `pavucontrol` (will be in package repos e.g. `apt` or `pacman`)
2. Launch and turn on Lyrebird
3. Open `pavucontrol`, go to "Recording"
4. Change the device listed next to SoX to your external mic

![Screenshot from 2021-01-12 13-39-49](https://user-images.githubusercontent.com/41309736/104321652-d3a04880-54db-11eb-93b9-c3f005d5f9d3.png)

Let me know how it goes :-)

**Comment by DarkStar1997** [comment]
Thanks for the quick reply! I'll let you know for sure when I try it.

**Comment by DarkStar1997** [comment]
It works fine!!! Thank you.
